### ISSUE TITLE
HTMLElement.shadowRoot is deprecated.

### ISSUE THREAD

**Issue by steventango** [puranjayjain/chrome-color-picker#19] opened 2017-07-30 22:02 UTC
The contents of `atom-text-editor` elements are no longer encapsulated
within a shadow DOM boundary. Please, stop using `shadowRoot` and access
the editor contents directly instead.
```
HTMLElement.shadowRoot (C:\Users\Steven\AppData\Local\atom\app-1.19.0-beta5\resources\app\src\text-editor-element.js:13:10)
Object.toggle (C:\Users\Steven\.atom\packages\chrome-color-picker\lib\chrome-color-picker.coffee:244:42)
HTMLElement.subscriptions.add.atom.commands.add.chrome-color-picker:toggle (C:\Users\Steven\.atom\packages\chrome-color-picker\lib\chrome-color-picker.coffee:117:26)
CommandRegistry.handleCommandEvent (<embedded>:21817:35)
handleCommandEvent (<embedded>:21555:65)
CommandRegistry.dispatch (<embedded>:21718:25)
```

**Comment by puranjayjain** [comment] 2017-07-31 02:39
duplicate of #15

**Closed as completed by puranjayjain** 2017-07-31 02:39 UTC

**Comment by brndto** [comment] 2018-07-19 03:01
Any movement on this? I use this extension frequently.

**Comment by puranjayjain** [comment] 2018-07-24 07:41
Hi @branditodesign  I'll look into this

**Comment by thehumangerm** [comment] 2018-11-11 03:09
still an issue

**Comment by xxyyzz2050** [comment] 2019-04-29 10:58
please fix

**Comment by VishwaJay** [comment] 2019-06-13 18:34
Still an issue.

**Comment by OldNick** [comment] 2019-11-21 00:29
Still an issue
It's a pity as it's the only decent colour picker

Maybe someone should fork it and sort it out... unfortunately I lack the expertise

**Comment by rrroyal** [comment] 2019-12-24 11:02
Fixed in #24. @puranjayjain please take a look at this one.

**Comment by puranjayjain** [comment] 2019-12-27 09:28
@rrroyal merged will release it with a tag to apm
