### ISSUE TITLE
i can't enable the plugin

### ISSUE THREAD

**Issue by cengizhan** [puranjayjain/chrome-color-picker#3] opened 2016-04-22 12:54 UTC
this plugin never runs for me. i cant enable it because it changes window sizes.

> [Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0-beta2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [chrome-color-picker](https://github.com/puranjayjain/chrome-color-picker) package, v0.5.1
### Stack Trace

Failed to load the chrome-color-picker package

```
At Recursive variable definition for @background in D:\App\Atom\user-data\packages\chrome-color-picker\styles\chrome-color-picker.less:16:735

LessError: Recursive variable definition for @background
  at D:\App\Atom\user-data\packages\chrome-color-picker\styles\chrome-color-picker.less:16:735
```
### Commands

```
     -8:25.6.0 settings-view:open (atom-text-editor.editor.mechanical-keyboard)
```
### Config

``` json
{
  "core": {
    "allowPendingPaneItems": false,
    "autoHideMenuBar": true,
    "automaticallyUpdate": false,
    "disabledPackages": [
      "language-coffee-script",
      "language-clojure",
      "language-go",
      "language-java",
      "language-mustache",
      "language-toml",
      "wrap-guide",
      "indent-guide-improved",
      "open-on-github",
      "archive-view",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-yaml",
      "package-generator",
      "spell-check",
      "altgr",
      "neon-cursor",
      "glowing-cursor",
      "deprecation-cop",
      "git-diff",
      "language-gfm",
      "language-make",
      "git-plus",
      "styleguide",
      "atom-minify",
      "synced-sidebar",
      "welcome",
      "metrics",
      "file-icons",
      "docblockr",
      "atom-autocomplete-php",
      "linter-jshint",
      "php-integrator-symbol-viewer",
      "atom-keyboard-macros",
      "linter-csslint",
      "chrome-color-picker"
    ],
    "packagesWithKeymapsDisabled": [
      "space-tab",
      "tool-bar",
      "atom-keyboard-macros"
    ],
    "themes": [
      "run-time-ui",
      "bliss-monokai-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
aligner, v0.21.0
aligner-css, v1.2.0
aligner-php, v1.0.0
aligner-scss, v1.1.0
atom-bracket-highlight, v0.3.1
atom-json-color, v0.4.2
atom-ternjs, v0.13.2
auto-indent, v0.5.0
autoclose-html, v0.23.0
bliss-monokai-syntax, v1.0.0
clean-context-menu, v0.3.1
color-picker, v2.1.1
cursor-history, v0.5.9
devdocs, v0.2.1
fast-duplicate, v1.4.0
file-watcher, v0.4.0
filecolor, v0.3.1
flex-tool-bar, v0.10.0
foldername-tabs, v0.1.11
highlight-line, v0.11.1
highlight-selected, v0.11.2
indentation-indicator, v0.6.0
inline-messenger, v1.2.8
johns-work-arounds, v0.34.0
jshint, v1.8.5
keyboard-localization, v1.4.18
keyboard-scroll, v0.4.0
less-than-slash, v0.13.0
linter, v1.11.4
linter-htmlhint, v1.1.4
linter-php, v1.2.0
linter-tidy, v2.1.0
mechanical-keyboard-1, v0.1.3
minimap, v4.22.1
minimap-bookmarks, v0.3.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-selection, v4.4.0
neon-selection, v0.3.2
php-cs-fixer, v2.5.6
php-integrator-annotations, v0.4.0
php-integrator-autocomplete-plus, v0.7.0
php-integrator-base, v0.8.1
php-integrator-call-tips, v0.2.3
php-integrator-linter, v0.2.2
php-integrator-navigation, v0.6.2
php-integrator-refactoring, v0.4.2
php-integrator-tooltips, v0.6.0
pigments, v0.26.0
pinned-tabs, v0.2.2
project-manager, v2.9.7
quick-docs, v0.1.0
rainbow-tabs, v2.2.1
react, v0.15.0
remember-file-positions, v0.2.2
remember-folds, v0.1.0
Remote-FTP, v0.7.20
run-time-ui, v13.37.3
symbols-tree-view, v0.12.0
tabs-to-spaces, v1.0.2
tag, v0.3.0
terminal-plus, v0.14.5
tool-bar, v0.4.0

# Dev
No dev packages
```

**Comment by puranjayjain** [comment] 2016-04-22 13:04
@cengizhan thanks for reporting it I'll look into it.

**Comment by puranjayjain** [comment] 2016-04-22 13:07
@cengizhan can I also know which ui and syntax theme you are using?

**Comment by puranjayjain** [comment] 2016-04-24 17:56
@cengizhan tried the picker on your configuration (windows 10 64 bit Pro and Atom 1.8.0-beta2) works perfectly. Can I know what UI theme and syntax theme you are using? Also if the issue is resolved can I close this issue here ?

**Comment by cengizhan** [comment] 2016-04-25 07:08
UI Theme: Run Time
Sytnax Theme: Bliss Monokai

btw v0.6.0 has the same problem

**Comment by cengizhan** [comment] 2016-04-25 07:16
This is what happens after i enable the plugin. plugin reduces my work space. also there is no color picker.

![untitled](https://cloud.githubusercontent.com/assets/1976368/14776319/9323e390-0ace-11e6-8337-2301e33d58a5.png)

**Comment by puranjayjain** [comment] 2016-04-25 09:52
Just fixed that, It will be resolved in the next release (0.7.0) :smile: . Also I see that you have another package enabled color-picker, make sure to disable their keybinding or change the keybinding
 of chrome-color-picker to prevent clashes 
![capture 6](https://cloud.githubusercontent.com/assets/5458094/14780152/38ad5150-0af9-11e6-95f7-a4301d948e34.PNG)

**Comment by puranjayjain** [comment] 2016-04-26 06:38
Feel free to reopen this issue or open a new one if this persists :smile:

**Closed as completed by puranjayjain** 2016-04-26 06:38 UTC
Labels: bug

**Comment by cengizhan** [comment] 2016-04-26 12:18
issue has been fixed. thanks.

can i recommend something? can you make previous/current color circles bigger? or may be make them squre and touch each other. so that we can distinguish the color difference clearly?

**Comment by puranjayjain** [comment] 2016-04-26 12:25
You something mean like this?
![image](https://cloud.githubusercontent.com/assets/5458094/14817961/005584aa-0bd8-11e6-8d1c-67f682889586.png)

**Comment by puranjayjain** [comment] 2016-04-26 12:29
@cengizhan can't make promisises but will try to do it before v1.0.0.Also, I'll leave it to the user to configure. Sounds good?

**Comment by cengizhan** [comment] 2016-04-26 12:45
yes. something like this. but bigger ones will be better. thanks again.

**Comment by puranjayjain** [comment] 2016-04-26 12:46
@cengizhan can you write all this and add a new issue? I mean what you require in a new issue, it will be really helpful and easy to track that way
